//
// GENERATED BY THE HUGEICONS PRO NPM CLI hugeicons-pro.
// DO NOT EDIT. CHANGES MAY BE OVERWRITTEN.
// FOR LICENSED USE ONLY.
//
// https://hugeicons.com
// https://hugeicons.com/license-agreement

export { GithubIcon } from "./GithubIcon"
export { InstagramIcon } from "./InstagramIcon"
export { Linkedin02Icon } from "./Linkedin02Icon"
export { NewTwitterIcon } from "./NewTwitterIcon"
